# Generated by Django 5.2.6 on 2026-06-04 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'مكالمة صوتية'), ('video', 'مكالمة فيديو')], default='audio', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'تم البدء'), ('ongoing', 'جارية'), ('completed', 'مكتملة'), ('missed', 'فائتة'), ('rejected', 'مرفوضة')], default='initiated', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مكالمة',
                'verbose_name_plural': 'المكالمات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
