# Generated by Django 5.2.6 on 2026-06-03 15:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('public', 'عامة'), ('private', 'خاصة'), ('group', 'مجموعة')], default='public', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=50)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_rooms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'غرفة دردشة',
                'verbose_name_plural': 'غرف الدردشة',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'room_type')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('file', 'ملف'), ('system', 'نظام')], default='text', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_for', models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_content', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='chat.message')),
            ],
            options={
                'verbose_name': 'سجل تعديل الرسالة',
                'verbose_name_plural': 'سجلات تعديل الرسائل',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_users', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlinestatuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مستخدم متصل',
                'verbose_name_plural': 'المستخدمون المتصلون',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😄'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠'), ('fire', '🔥'), ('clap', '👏')], max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رد فعل',
                'verbose_name_plural': 'ردود الفعل',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'دعوة غرفة',
                'verbose_name_plural': 'دعوات الغرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_typing', models.BooleanField(default=False)),
                ('last_typed', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حالة الكتابة',
                'verbose_name_plural': 'حالات الكتابة',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('status', models.CharField(choices=[('online', 'متصل'), ('away', 'بعيد'), ('busy', 'مشغول'), ('offline', 'غير متصل')], default='online', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('auto', 'تلقائي')], default='light', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='chat_messag_room_id_645da7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='chat_messag_sender__b20cde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineuser',
            unique_together={('user', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='roominvitation',
            unique_together={('room', 'invited_user')},
        ),
        migrations.AlterUniqueTogether(
            name='typingstatus',
            unique_together={('room', 'user')},
        ),
    ]
