# Generated by Django 5.2.7 on 2025-10-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_onlineuser_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='roominvitation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='onlineuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roominvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typingstatus',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='typingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
