# Generated by Django 5.2.7 on 2025-10-12 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_roominvitation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominvitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'دعوة غرفة', 'verbose_name_plural': 'دعوات الغرف'},
        ),
        migrations.AddField(
            model_name='roominvitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onlineuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlinestatuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roominvitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
